### ISSUE TITLE
code samples not visible until reloaded

### ISSUE THREAD

**Issue by calendee** [deckgo/deckdeckgo#1057] opened 2021-01-18 08:01 UTC
### Documentation Feedback

When viewing the documentation at the link below, the code samples don't display the code.

After refreshing the page, the code displays.

Affected Browsers: Safari, Safari Developer Preview, Opera, Firefox, Firefox Developer Edition

![deckdeckgo-docs-missing-code](https://user-images.githubusercontent.com/57374/104887529-52c1d080-5963-11eb-801a-fa53183ec7f6.png)

**Affected documentation page:** https://docs.deckdeckgo.com/docs/#app-introduction-starting-a-new-presentation

**Comment by peterpeterparker** [comment] 2021-01-18 08:10
Thanks for the issue @calendee !

Probably due to the language `bash` I had set to the examples. I should check what's wrong there...

**Comment by peterpeterparker** [comment] 2021-01-25 16:28
It has to do with the download of extra languages but, I was not able to reproduce / debug the issue.

When I try locally, everything went fine. I am guessing there  is a race condition between  attaching DOM elements and fetching extra script. That or an issue with Service Worker.

**Comment by peterpeterparker** [comment] 2021-06-13 15:03
The documentation has been moved from a custom made app to Storybook, therefore this issue should no longer exists.
That's why I close the issue. Thx again for reporting it!

**Closed by peterpeterparker** 2021-06-13 15:03 UTC
Labels: bug, docs
