### ISSUE TITLE
Code Block with HTML seems to parse it wrong

### ISSUE THREAD

**Issue by iamandrewluca** [deckgo/deckdeckgo#1208] opened 2021-06-17 18:22 UTC
### Affected part of DeckDeckGo

- [x] Studio (online editor)

### Reproduction (click for YouTube video)

[![DeckDeckGo code block issue, youtube video](https://i3.ytimg.com/vi/_gj7zGFL7N8/hqdefault.jpg)](https://youtu.be/_gj7zGFL7N8)

### Expected Behavior

- After publish code block should contain the same code content
- On edit code blocks should not miss code content

### Actual Behavior

- After publish some code blocks miss content
- On edit some code blocks miss content

### Environment

- Browser: Chrome Version 91.0.4472.77 (Official Build) (64-bit)
- Operating System: Ubuntu 20.04.2 LTS

**Comment by iamandrewluca** [comment] 2021-06-17 18:28
I tried with a new presentation.

- Create new presentation
- Add new slide Title + Code Block
- Change code block hightlighting to HTML
- Add this code block
```html
<template>
  <div>test</div>
</template>
```
- Publish.
- Open published presentation
- Slide looks fine
- Go back to editor
- Close presentation
- Open it again
- Code block contains only `<template></template>`

**Comment by peterpeterparker** [comment] 2021-06-18 13:50
The issue is the following: the `<template/>` was correctly copied to the slotted element but, is interpreted by the browser. Therefore its content becomes added underneath a `#document-fragment` which cannot be read when we save the slide to the db.

This will be solved in #1209 by escaping characters.

**Comment by iamandrewluca** [comment] 2021-06-18 13:57
@peterpeterparker thanks a lot! looking forward to create more presentations in DeckDeckGo :)

**Comment by peterpeterparker** [comment] 2021-06-18 13:59
Awesome and my pleasure, thanks for the help!

I spotted another small thing which I am trying to solve in same PR. Will ping you when merged and deployed.

**Closed** 2021-06-18 16:16 UTC
Labels: bug, highlight-code, studio

**Comment by peterpeterparker** [comment] 2021-06-18 16:21
Solved and live 😃

Thanks a lot for the detailed issue Andrew! If you notice any related or other issues, let me know.
