### ISSUE TITLE
Maintain Aspect Ratio with DRR

### ISSUE THREAD

**Issue by gregmax17** [deckgo/deckdeckgo#1483] opened 2022-02-24 21:50 UTC
Like the title states, is there a way to maintain the aspect ratio when using the drag, resize, and rotate component?

**Comment by peterpeterparker** [comment] 2022-02-25 06:37
Not at the moment and not in our plan (as you can see the duplicate of this question is quite old #657). PR of course welcome 😉.

**Closed by peterpeterparker** 2022-02-25 06:37 UTC
